import { Sparkles } from 'lucide-react';

export default function AIGeneratedBadge() {
  return (
    <div className="border-border/80 inline-flex items-center gap-1 rounded-full border bg-secondary px-2 py-1 text-xs font-medium text-primary">
      <Sparkles className="h-3 w-3" />
      <span>Generated by AI</span>
    </div>
  );
}
