import { Sparkles } from 'lucide-react';

export default function AIGeneratedBadge() {
  return (
    <div className="inline-flex items-center gap-1 rounded-full border border-gray-200 bg-gray-100 px-2 py-1 text-xs font-medium text-gray-600">
      <Sparkles className="h-3 w-3" />
      <span>Generated by AI</span>
    </div>
  );
}
